version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace
    ports:
      - "3000:3005"
    volumes:
      - .:/app
      - /app/node_modules
